apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
spec:
  type: NodePort
  selector:
    app: docker-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
