apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
  labels:
    app: docker-app
spec:
  type: NodePort
  selector:
    app: docker-app
  ports:
    - protocol: TCP
      port: 80        # service port (inside cluster)
      targetPort: 3000 # port container listens on
      nodePort: 30080 # optional: specific nodeport (30000-32767). You can omit to let k8s choose one.
