name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker tag myapp:latest usvaqandeel/myapp:latest
          docker push usvaqandeel/myapp:latest

          # âœ… OPTIONAL Railway Deploy
      - name: Deploy to Railway
        if: ${{ secrets.RAILWAY_TOKEN != '' }}
        uses: railwayapp/action@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}
          environment: production
          service: myapp
