name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  test-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Testing
      - name: Run Tests
        run: echo "ğŸ§ª Running tests..." 

      # 2. Build
      - name: Build Project
        run: echo "ğŸ—ï¸ Building project..."

      # 3. Build Docker Image
      - name: Build Docker Image
        run: docker build -t mydockerusername/my-app:latest .

      # 4. Notify
      - name: Notify
        run: echo "âœ… All steps completed successfully!"
